### ISSUE TITLE
Could not open error

### ISSUE THREAD

**Issue by povnz** [SuslikV/untrunc-w#19]
Hey man,

Thanks for your work on this, I've been looking for a windows build of untrunc-w everywhere.....

D:\Clients\FOLDER\Footage\C001_A7sOLD\PRIVATE\M4ROOT\CLIP>untrunc-w.exe C0001.MP4 [B0001.MP4]
GOP count to build the interleaving mask: 1
GOP count to loop the interleaving mask: 1
Samples per chunk (0 - get it from the working file): 0
Reading working file: C0001.MP4
(C0001.MP4) file size= 3357314725 bytes
AV log level: 8
number of entries (stts) = 1
number of entries (stss) = 401
number of entries (stsz) = 9612
Samples size: MIN 76816; MAX 1667203
number of entries (stco) = 801
number of entries (stsc) = 1
Track 0, codecID= 28
number of entries (stts) = 1
number of entries (stsz) = 18455040
Samples size: MIN 4; MAX 4
number of entries (stco) = 801
number of entries (stsc) = 1
Track 1, codecID= 65537
number of entries (stts) = 1
number of entries (stsz) = 9612
Samples size: MIN 1024; MAX 1024
number of entries (stco) = 801
number of entries (stsc) = 1
Track 2, codecID= 0
Base track: 0
baseTrack.keyframes.size(): 401
Number of chunks to build the mask, trying: 25
Actual IM size = 73
Chunks interleaving Mask (track's #):
2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2
Chunks interleaving Mask second loop (track's #):
2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2
Samples per each chunk Mask (samples count):
12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12
Samples per each chunk Mask second loop (samples count):
12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12 12 23040 12
Could not open file to repair: [B0001.MP4]

Any ideas what I'm doing wrong, ???

I can get the demo version of this to work: http://grauonline.de/cms2/?page_id=5
So its defiantly possible to untrunc the file

Do you think i installed it incorrectly ?

**Comment by SuslikV** [comment]
First,
> Track 1, codecID= 65537

The codec unknown to the untrunc-w, so there is no optimizations to recover the samples. It seems to be some kind of PCM audio, so I can try to recover the files manually by splitting the file at each point where sample size changes (if any).

---
The next is
> Track 2, codecID= 0

the stream is unknown to the program and I cannot say if the recovery will be started at all. I need to look at the actual samples.

---
And finally, the error you see,
> Could not open file to repair: [B0001.MP4]

it's just because of the mentioned file name `[B0001.MP4]`
The square brackets, in usage, means that the string is optional and may be omitted. Just use `B0001.MP4` (without the brackets).

---
Possible solution:

1. Fix the command line string you gave to the program.
2. Try few different working files.
3. If recovery interrupts on next audio sample, try to split the file manually (by cutting unneeded parts) and look for the next video sample (not easy task, so...).

If you don't mind, I can try to recover your files, find me ("Suslik V") at the https://obsproject.com via private messaging conversation for this.
